### ISSUE TITLE
Rainbow

### ISSUE THREAD

**Issue by Hilmaar** [guttih/voffcon#58]
Leyfa notanda að velja liti sem að rainbow kerfið notar

(kannski sýna color spectrum stiku og notandi getur afmarkað eitt (og fleiri) svið á spectrum stikunni)

**Comment by guttih** [comment]
Góð hugmynd fyrir forritið sem hlaðið er upp á esp32.  Þetta forrit er ekki eiginlegur hluti af VoffCon heldur cusomized forrit sem notar VoffCon.

En það vill þannig til að þetta forrit er líka á github og hægt er að finna það hér: https://github.com/guttih/ledDeviceServerEsp32.

Ég held að einnig ætti ég að setja í þann repo, controlið og kortið fyrir það.  
Ég set það sem feature request á ledDeviceServerEsp32 repoinn.
